runtime: python311

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.6

handlers:
- url: /.*
  script: auto

entrypoint: gunicorn -w 2 -b 0.0.0.0:$PORT --timeout 120 app.main:app

